name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known hosts
        run: |
          ssh-keyscan -H 8.215.22.182 >> ~/.ssh/known_hosts

      - name: Copy files to server
        run: |
          scp -r ./ root@8.215.22.182:/root/.ssh/backend-pomodoro

      - name: SSH commands to restart app using PM2
        run: |
          ssh root@8.215.22.182 << 'EOF'
          cd /root/.ssh/backend-pomodoro
          git pull origin main
          npm install
          pm2 restart backend-pomodoro
          EOF
